/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.and_expression;
import org.xtext.example.mydsl.myDsl.and_expressionR;
import org.xtext.example.mydsl.myDsl.equality_expression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>and expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.and_expressionImpl#getEquality_expression <em>Equality expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.and_expressionImpl#getAnd_expressionR <em>And expression R</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class and_expressionImpl extends MinimalEObjectImpl.Container implements and_expression
{
  /**
   * The cached value of the '{@link #getEquality_expression() <em>Equality expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEquality_expression()
   * @generated
   * @ordered
   */
  protected equality_expression equality_expression;

  /**
   * The cached value of the '{@link #getAnd_expressionR() <em>And expression R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnd_expressionR()
   * @generated
   * @ordered
   */
  protected and_expressionR and_expressionR;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected and_expressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.AND_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public equality_expression getEquality_expression()
  {
    return equality_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetEquality_expression(equality_expression newEquality_expression, NotificationChain msgs)
  {
    equality_expression oldEquality_expression = equality_expression;
    equality_expression = newEquality_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION, oldEquality_expression, newEquality_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEquality_expression(equality_expression newEquality_expression)
  {
    if (newEquality_expression != equality_expression)
    {
      NotificationChain msgs = null;
      if (equality_expression != null)
        msgs = ((InternalEObject)equality_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION, null, msgs);
      if (newEquality_expression != null)
        msgs = ((InternalEObject)newEquality_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION, null, msgs);
      msgs = basicSetEquality_expression(newEquality_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION, newEquality_expression, newEquality_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public and_expressionR getAnd_expressionR()
  {
    return and_expressionR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAnd_expressionR(and_expressionR newAnd_expressionR, NotificationChain msgs)
  {
    and_expressionR oldAnd_expressionR = and_expressionR;
    and_expressionR = newAnd_expressionR;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R, oldAnd_expressionR, newAnd_expressionR);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAnd_expressionR(and_expressionR newAnd_expressionR)
  {
    if (newAnd_expressionR != and_expressionR)
    {
      NotificationChain msgs = null;
      if (and_expressionR != null)
        msgs = ((InternalEObject)and_expressionR).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R, null, msgs);
      if (newAnd_expressionR != null)
        msgs = ((InternalEObject)newAnd_expressionR).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R, null, msgs);
      msgs = basicSetAnd_expressionR(newAnd_expressionR, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R, newAnd_expressionR, newAnd_expressionR));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION:
        return basicSetEquality_expression(null, msgs);
      case MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R:
        return basicSetAnd_expressionR(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION:
        return getEquality_expression();
      case MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R:
        return getAnd_expressionR();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION:
        setEquality_expression((equality_expression)newValue);
        return;
      case MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R:
        setAnd_expressionR((and_expressionR)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION:
        setEquality_expression((equality_expression)null);
        return;
      case MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R:
        setAnd_expressionR((and_expressionR)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.AND_EXPRESSION__EQUALITY_EXPRESSION:
        return equality_expression != null;
      case MyDslPackage.AND_EXPRESSION__AND_EXPRESSION_R:
        return and_expressionR != null;
    }
    return super.eIsSet(featureID);
  }

} //and_expressionImpl
