/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.and_expression;
import org.xtext.example.mydsl.myDsl.exclusive_or_expressionR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>exclusive or expression R</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.exclusive_or_expressionRImpl#getAnd_expression <em>And expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.exclusive_or_expressionRImpl#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class exclusive_or_expressionRImpl extends MinimalEObjectImpl.Container implements exclusive_or_expressionR
{
  /**
   * The cached value of the '{@link #getAnd_expression() <em>And expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnd_expression()
   * @generated
   * @ordered
   */
  protected and_expression and_expression;

  /**
   * The cached value of the '{@link #getRec() <em>Rec</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRec()
   * @generated
   * @ordered
   */
  protected EList<exclusive_or_expressionR> rec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected exclusive_or_expressionRImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.EXCLUSIVE_OR_EXPRESSION_R;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public and_expression getAnd_expression()
  {
    return and_expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAnd_expression(and_expression newAnd_expression, NotificationChain msgs)
  {
    and_expression oldAnd_expression = and_expression;
    and_expression = newAnd_expression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION, oldAnd_expression, newAnd_expression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAnd_expression(and_expression newAnd_expression)
  {
    if (newAnd_expression != and_expression)
    {
      NotificationChain msgs = null;
      if (and_expression != null)
        msgs = ((InternalEObject)and_expression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION, null, msgs);
      if (newAnd_expression != null)
        msgs = ((InternalEObject)newAnd_expression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION, null, msgs);
      msgs = basicSetAnd_expression(newAnd_expression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION, newAnd_expression, newAnd_expression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<exclusive_or_expressionR> getRec()
  {
    if (rec == null)
    {
      rec = new EObjectContainmentEList<exclusive_or_expressionR>(exclusive_or_expressionR.class, this, MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__REC);
    }
    return rec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION:
        return basicSetAnd_expression(null, msgs);
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__REC:
        return ((InternalEList<?>)getRec()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION:
        return getAnd_expression();
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__REC:
        return getRec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION:
        setAnd_expression((and_expression)newValue);
        return;
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__REC:
        getRec().clear();
        getRec().addAll((Collection<? extends exclusive_or_expressionR>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION:
        setAnd_expression((and_expression)null);
        return;
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__REC:
        getRec().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__AND_EXPRESSION:
        return and_expression != null;
      case MyDslPackage.EXCLUSIVE_OR_EXPRESSION_R__REC:
        return rec != null && !rec.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //exclusive_or_expressionRImpl
