/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.designation;
import org.xtext.example.mydsl.myDsl.initializer;
import org.xtext.example.mydsl.myDsl.initializer_list;
import org.xtext.example.mydsl.myDsl.initializer_listR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>initializer list</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listImpl#getDesignation <em>Designation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listImpl#getInitializer <em>Initializer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listImpl#getIl <em>Il</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listImpl#getIlr <em>Ilr</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class initializer_listImpl extends initializerImpl implements initializer_list
{
  /**
   * The cached value of the '{@link #getDesignation() <em>Designation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesignation()
   * @generated
   * @ordered
   */
  protected designation designation;

  /**
   * The cached value of the '{@link #getInitializer() <em>Initializer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitializer()
   * @generated
   * @ordered
   */
  protected initializer initializer;

  /**
   * The cached value of the '{@link #getIl() <em>Il</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIl()
   * @generated
   * @ordered
   */
  protected initializer_listR il;

  /**
   * The cached value of the '{@link #getIlr() <em>Ilr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIlr()
   * @generated
   * @ordered
   */
  protected initializer_listR ilr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected initializer_listImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INITIALIZER_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public designation getDesignation()
  {
    return designation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDesignation(designation newDesignation, NotificationChain msgs)
  {
    designation oldDesignation = designation;
    designation = newDesignation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__DESIGNATION, oldDesignation, newDesignation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDesignation(designation newDesignation)
  {
    if (newDesignation != designation)
    {
      NotificationChain msgs = null;
      if (designation != null)
        msgs = ((InternalEObject)designation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__DESIGNATION, null, msgs);
      if (newDesignation != null)
        msgs = ((InternalEObject)newDesignation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__DESIGNATION, null, msgs);
      msgs = basicSetDesignation(newDesignation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__DESIGNATION, newDesignation, newDesignation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public initializer getInitializer()
  {
    return initializer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitializer(initializer newInitializer, NotificationChain msgs)
  {
    initializer oldInitializer = initializer;
    initializer = newInitializer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__INITIALIZER, oldInitializer, newInitializer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInitializer(initializer newInitializer)
  {
    if (newInitializer != initializer)
    {
      NotificationChain msgs = null;
      if (initializer != null)
        msgs = ((InternalEObject)initializer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__INITIALIZER, null, msgs);
      if (newInitializer != null)
        msgs = ((InternalEObject)newInitializer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__INITIALIZER, null, msgs);
      msgs = basicSetInitializer(newInitializer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__INITIALIZER, newInitializer, newInitializer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public initializer_listR getIl()
  {
    return il;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIl(initializer_listR newIl, NotificationChain msgs)
  {
    initializer_listR oldIl = il;
    il = newIl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__IL, oldIl, newIl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIl(initializer_listR newIl)
  {
    if (newIl != il)
    {
      NotificationChain msgs = null;
      if (il != null)
        msgs = ((InternalEObject)il).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__IL, null, msgs);
      if (newIl != null)
        msgs = ((InternalEObject)newIl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__IL, null, msgs);
      msgs = basicSetIl(newIl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__IL, newIl, newIl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public initializer_listR getIlr()
  {
    return ilr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIlr(initializer_listR newIlr, NotificationChain msgs)
  {
    initializer_listR oldIlr = ilr;
    ilr = newIlr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__ILR, oldIlr, newIlr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIlr(initializer_listR newIlr)
  {
    if (newIlr != ilr)
    {
      NotificationChain msgs = null;
      if (ilr != null)
        msgs = ((InternalEObject)ilr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__ILR, null, msgs);
      if (newIlr != null)
        msgs = ((InternalEObject)newIlr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST__ILR, null, msgs);
      msgs = basicSetIlr(newIlr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST__ILR, newIlr, newIlr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST__DESIGNATION:
        return basicSetDesignation(null, msgs);
      case MyDslPackage.INITIALIZER_LIST__INITIALIZER:
        return basicSetInitializer(null, msgs);
      case MyDslPackage.INITIALIZER_LIST__IL:
        return basicSetIl(null, msgs);
      case MyDslPackage.INITIALIZER_LIST__ILR:
        return basicSetIlr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST__DESIGNATION:
        return getDesignation();
      case MyDslPackage.INITIALIZER_LIST__INITIALIZER:
        return getInitializer();
      case MyDslPackage.INITIALIZER_LIST__IL:
        return getIl();
      case MyDslPackage.INITIALIZER_LIST__ILR:
        return getIlr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST__DESIGNATION:
        setDesignation((designation)newValue);
        return;
      case MyDslPackage.INITIALIZER_LIST__INITIALIZER:
        setInitializer((initializer)newValue);
        return;
      case MyDslPackage.INITIALIZER_LIST__IL:
        setIl((initializer_listR)newValue);
        return;
      case MyDslPackage.INITIALIZER_LIST__ILR:
        setIlr((initializer_listR)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST__DESIGNATION:
        setDesignation((designation)null);
        return;
      case MyDslPackage.INITIALIZER_LIST__INITIALIZER:
        setInitializer((initializer)null);
        return;
      case MyDslPackage.INITIALIZER_LIST__IL:
        setIl((initializer_listR)null);
        return;
      case MyDslPackage.INITIALIZER_LIST__ILR:
        setIlr((initializer_listR)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST__DESIGNATION:
        return designation != null;
      case MyDslPackage.INITIALIZER_LIST__INITIALIZER:
        return initializer != null;
      case MyDslPackage.INITIALIZER_LIST__IL:
        return il != null;
      case MyDslPackage.INITIALIZER_LIST__ILR:
        return ilr != null;
    }
    return super.eIsSet(featureID);
  }

} //initializer_listImpl
