/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.init_declarator;
import org.xtext.example.mydsl.myDsl.init_declarator_listR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>init declarator list R</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.init_declarator_listRImpl#getInit_declarator <em>Init declarator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.init_declarator_listRImpl#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class init_declarator_listRImpl extends MinimalEObjectImpl.Container implements init_declarator_listR
{
  /**
   * The cached value of the '{@link #getInit_declarator() <em>Init declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInit_declarator()
   * @generated
   * @ordered
   */
  protected init_declarator init_declarator;

  /**
   * The cached value of the '{@link #getRec() <em>Rec</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRec()
   * @generated
   * @ordered
   */
  protected EList<init_declarator_listR> rec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected init_declarator_listRImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INIT_DECLARATOR_LIST_R;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public init_declarator getInit_declarator()
  {
    return init_declarator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInit_declarator(init_declarator newInit_declarator, NotificationChain msgs)
  {
    init_declarator oldInit_declarator = init_declarator;
    init_declarator = newInit_declarator;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR, oldInit_declarator, newInit_declarator);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInit_declarator(init_declarator newInit_declarator)
  {
    if (newInit_declarator != init_declarator)
    {
      NotificationChain msgs = null;
      if (init_declarator != null)
        msgs = ((InternalEObject)init_declarator).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR, null, msgs);
      if (newInit_declarator != null)
        msgs = ((InternalEObject)newInit_declarator).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR, null, msgs);
      msgs = basicSetInit_declarator(newInit_declarator, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR, newInit_declarator, newInit_declarator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<init_declarator_listR> getRec()
  {
    if (rec == null)
    {
      rec = new EObjectContainmentEList<init_declarator_listR>(init_declarator_listR.class, this, MyDslPackage.INIT_DECLARATOR_LIST_R__REC);
    }
    return rec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR:
        return basicSetInit_declarator(null, msgs);
      case MyDslPackage.INIT_DECLARATOR_LIST_R__REC:
        return ((InternalEList<?>)getRec()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR:
        return getInit_declarator();
      case MyDslPackage.INIT_DECLARATOR_LIST_R__REC:
        return getRec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR:
        setInit_declarator((init_declarator)newValue);
        return;
      case MyDslPackage.INIT_DECLARATOR_LIST_R__REC:
        getRec().clear();
        getRec().addAll((Collection<? extends init_declarator_listR>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR:
        setInit_declarator((init_declarator)null);
        return;
      case MyDslPackage.INIT_DECLARATOR_LIST_R__REC:
        getRec().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INIT_DECLARATOR_LIST_R__INIT_DECLARATOR:
        return init_declarator != null;
      case MyDslPackage.INIT_DECLARATOR_LIST_R__REC:
        return rec != null && !rec.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //init_declarator_listRImpl
