/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.designation;
import org.xtext.example.mydsl.myDsl.initializer;
import org.xtext.example.mydsl.myDsl.initializer_listR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>initializer list R</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listRImpl#getDesignation <em>Designation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listRImpl#getInitializer <em>Initializer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.initializer_listRImpl#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class initializer_listRImpl extends MinimalEObjectImpl.Container implements initializer_listR
{
  /**
   * The cached value of the '{@link #getDesignation() <em>Designation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDesignation()
   * @generated
   * @ordered
   */
  protected designation designation;

  /**
   * The cached value of the '{@link #getInitializer() <em>Initializer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInitializer()
   * @generated
   * @ordered
   */
  protected initializer initializer;

  /**
   * The cached value of the '{@link #getRec() <em>Rec</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRec()
   * @generated
   * @ordered
   */
  protected EList<initializer_listR> rec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected initializer_listRImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.INITIALIZER_LIST_R;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public designation getDesignation()
  {
    return designation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDesignation(designation newDesignation, NotificationChain msgs)
  {
    designation oldDesignation = designation;
    designation = newDesignation;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_R__DESIGNATION, oldDesignation, newDesignation);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDesignation(designation newDesignation)
  {
    if (newDesignation != designation)
    {
      NotificationChain msgs = null;
      if (designation != null)
        msgs = ((InternalEObject)designation).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_R__DESIGNATION, null, msgs);
      if (newDesignation != null)
        msgs = ((InternalEObject)newDesignation).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_R__DESIGNATION, null, msgs);
      msgs = basicSetDesignation(newDesignation, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_R__DESIGNATION, newDesignation, newDesignation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public initializer getInitializer()
  {
    return initializer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInitializer(initializer newInitializer, NotificationChain msgs)
  {
    initializer oldInitializer = initializer;
    initializer = newInitializer;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_R__INITIALIZER, oldInitializer, newInitializer);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setInitializer(initializer newInitializer)
  {
    if (newInitializer != initializer)
    {
      NotificationChain msgs = null;
      if (initializer != null)
        msgs = ((InternalEObject)initializer).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_R__INITIALIZER, null, msgs);
      if (newInitializer != null)
        msgs = ((InternalEObject)newInitializer).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.INITIALIZER_LIST_R__INITIALIZER, null, msgs);
      msgs = basicSetInitializer(newInitializer, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.INITIALIZER_LIST_R__INITIALIZER, newInitializer, newInitializer));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<initializer_listR> getRec()
  {
    if (rec == null)
    {
      rec = new EObjectContainmentEList<initializer_listR>(initializer_listR.class, this, MyDslPackage.INITIALIZER_LIST_R__REC);
    }
    return rec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_R__DESIGNATION:
        return basicSetDesignation(null, msgs);
      case MyDslPackage.INITIALIZER_LIST_R__INITIALIZER:
        return basicSetInitializer(null, msgs);
      case MyDslPackage.INITIALIZER_LIST_R__REC:
        return ((InternalEList<?>)getRec()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_R__DESIGNATION:
        return getDesignation();
      case MyDslPackage.INITIALIZER_LIST_R__INITIALIZER:
        return getInitializer();
      case MyDslPackage.INITIALIZER_LIST_R__REC:
        return getRec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_R__DESIGNATION:
        setDesignation((designation)newValue);
        return;
      case MyDslPackage.INITIALIZER_LIST_R__INITIALIZER:
        setInitializer((initializer)newValue);
        return;
      case MyDslPackage.INITIALIZER_LIST_R__REC:
        getRec().clear();
        getRec().addAll((Collection<? extends initializer_listR>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_R__DESIGNATION:
        setDesignation((designation)null);
        return;
      case MyDslPackage.INITIALIZER_LIST_R__INITIALIZER:
        setInitializer((initializer)null);
        return;
      case MyDslPackage.INITIALIZER_LIST_R__REC:
        getRec().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.INITIALIZER_LIST_R__DESIGNATION:
        return designation != null;
      case MyDslPackage.INITIALIZER_LIST_R__INITIALIZER:
        return initializer != null;
      case MyDslPackage.INITIALIZER_LIST_R__REC:
        return rec != null && !rec.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //initializer_listRImpl
