/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.external_declaration;
import org.xtext.example.mydsl.myDsl.translation_unitR;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>translation unit R</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.translation_unitRImpl#getExternal_declaration <em>External declaration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.translation_unitRImpl#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class translation_unitRImpl extends MinimalEObjectImpl.Container implements translation_unitR
{
  /**
   * The cached value of the '{@link #getExternal_declaration() <em>External declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExternal_declaration()
   * @generated
   * @ordered
   */
  protected external_declaration external_declaration;

  /**
   * The cached value of the '{@link #getRec() <em>Rec</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRec()
   * @generated
   * @ordered
   */
  protected EList<translation_unitR> rec;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected translation_unitRImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TRANSLATION_UNIT_R;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public external_declaration getExternal_declaration()
  {
    return external_declaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetExternal_declaration(external_declaration newExternal_declaration, NotificationChain msgs)
  {
    external_declaration oldExternal_declaration = external_declaration;
    external_declaration = newExternal_declaration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION, oldExternal_declaration, newExternal_declaration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExternal_declaration(external_declaration newExternal_declaration)
  {
    if (newExternal_declaration != external_declaration)
    {
      NotificationChain msgs = null;
      if (external_declaration != null)
        msgs = ((InternalEObject)external_declaration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION, null, msgs);
      if (newExternal_declaration != null)
        msgs = ((InternalEObject)newExternal_declaration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION, null, msgs);
      msgs = basicSetExternal_declaration(newExternal_declaration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION, newExternal_declaration, newExternal_declaration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<translation_unitR> getRec()
  {
    if (rec == null)
    {
      rec = new EObjectContainmentEList<translation_unitR>(translation_unitR.class, this, MyDslPackage.TRANSLATION_UNIT_R__REC);
    }
    return rec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION:
        return basicSetExternal_declaration(null, msgs);
      case MyDslPackage.TRANSLATION_UNIT_R__REC:
        return ((InternalEList<?>)getRec()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION:
        return getExternal_declaration();
      case MyDslPackage.TRANSLATION_UNIT_R__REC:
        return getRec();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION:
        setExternal_declaration((external_declaration)newValue);
        return;
      case MyDslPackage.TRANSLATION_UNIT_R__REC:
        getRec().clear();
        getRec().addAll((Collection<? extends translation_unitR>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION:
        setExternal_declaration((external_declaration)null);
        return;
      case MyDslPackage.TRANSLATION_UNIT_R__REC:
        getRec().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.TRANSLATION_UNIT_R__EXTERNAL_DECLARATION:
        return external_declaration != null;
      case MyDslPackage.TRANSLATION_UNIT_R__REC:
        return rec != null && !rec.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //translation_unitRImpl
