/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>additive expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression#getShift_expressionR <em>Shift expression R</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression#getMultiplicative_expression <em>Multiplicative expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.additive_expression#getAdditive_expressionR <em>Additive expression R</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression()
 * @model
 * @generated
 */
public interface additive_expression extends shift_expression
{
  /**
   * Returns the value of the '<em><b>Shift expression R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Shift expression R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shift expression R</em>' containment reference.
   * @see #setShift_expressionR(shift_expressionR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_Shift_expressionR()
   * @model containment="true"
   * @generated
   */
  shift_expressionR getShift_expressionR();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression#getShift_expressionR <em>Shift expression R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shift expression R</em>' containment reference.
   * @see #getShift_expressionR()
   * @generated
   */
  void setShift_expressionR(shift_expressionR value);

  /**
   * Returns the value of the '<em><b>Multiplicative expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Multiplicative expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicative expression</em>' containment reference.
   * @see #setMultiplicative_expression(multiplicative_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_Multiplicative_expression()
   * @model containment="true"
   * @generated
   */
  multiplicative_expression getMultiplicative_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression#getMultiplicative_expression <em>Multiplicative expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicative expression</em>' containment reference.
   * @see #getMultiplicative_expression()
   * @generated
   */
  void setMultiplicative_expression(multiplicative_expression value);

  /**
   * Returns the value of the '<em><b>Additive expression R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Additive expression R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additive expression R</em>' containment reference.
   * @see #setAdditive_expressionR(additive_expressionR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getadditive_expression_Additive_expressionR()
   * @model containment="true"
   * @generated
   */
  additive_expressionR getAdditive_expressionR();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.additive_expression#getAdditive_expressionR <em>Additive expression R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additive expression R</em>' containment reference.
   * @see #getAdditive_expressionR()
   * @generated
   */
  void setAdditive_expressionR(additive_expressionR value);

} // additive_expression
