/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>atomic type specifier</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getatomic_type_specifier()
 * @model
 * @generated
 */
public interface atomic_type_specifier extends type_specifier
{
} // atomic_type_specifier
