/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>block item list R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.block_item_listR#getBlock_item <em>Block item</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.block_item_listR#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getblock_item_listR()
 * @model
 * @generated
 */
public interface block_item_listR extends EObject
{
  /**
   * Returns the value of the '<em><b>Block item</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Block item</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Block item</em>' containment reference.
   * @see #setBlock_item(block_item)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getblock_item_listR_Block_item()
   * @model containment="true"
   * @generated
   */
  block_item getBlock_item();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.block_item_listR#getBlock_item <em>Block item</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Block item</em>' containment reference.
   * @see #getBlock_item()
   * @generated
   */
  void setBlock_item(block_item value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.block_item_listR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getblock_item_listR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<block_item_listR> getRec();

} // block_item_listR
