/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>constant expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getconstant_expression()
 * @model
 * @generated
 */
public interface constant_expression extends designator, struct_declarator, static_assert_declaration
{
} // constant_expression
