/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>declarator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declarator#getPointer <em>Pointer</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.declarator#getDd <em>Dd</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclarator()
 * @model
 * @generated
 */
public interface declarator extends init_declarator, struct_declarator
{
  /**
   * Returns the value of the '<em><b>Pointer</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pointer</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pointer</em>' containment reference.
   * @see #setPointer(pointer)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclarator_Pointer()
   * @model containment="true"
   * @generated
   */
  pointer getPointer();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.declarator#getPointer <em>Pointer</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pointer</em>' containment reference.
   * @see #getPointer()
   * @generated
   */
  void setPointer(pointer value);

  /**
   * Returns the value of the '<em><b>Dd</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dd</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dd</em>' containment reference.
   * @see #setDd(direct_declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdeclarator_Dd()
   * @model containment="true"
   * @generated
   */
  direct_declarator getDd();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.declarator#getDd <em>Dd</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dd</em>' containment reference.
   * @see #getDd()
   * @generated
   */
  void setDd(direct_declarator value);

} // declarator
