/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>direct declarator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.direct_declarator#getDirect_declaratorR <em>Direct declarator R</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdirect_declarator()
 * @model
 * @generated
 */
public interface direct_declarator extends declarator
{
  /**
   * Returns the value of the '<em><b>Direct declarator R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Direct declarator R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Direct declarator R</em>' containment reference.
   * @see #setDirect_declaratorR(direct_declaratorR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getdirect_declarator_Direct_declaratorR()
   * @model containment="true"
   * @generated
   */
  direct_declaratorR getDirect_declaratorR();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.direct_declarator#getDirect_declaratorR <em>Direct declarator R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Direct declarator R</em>' containment reference.
   * @see #getDirect_declaratorR()
   * @generated
   */
  void setDirect_declaratorR(direct_declaratorR value);

} // direct_declarator
