/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>equality expression R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.equality_expressionR#getRelational_expression <em>Relational expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.equality_expressionR#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getequality_expressionR()
 * @model
 * @generated
 */
public interface equality_expressionR extends EObject
{
  /**
   * Returns the value of the '<em><b>Relational expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relational expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relational expression</em>' containment reference.
   * @see #setRelational_expression(relational_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getequality_expressionR_Relational_expression()
   * @model containment="true"
   * @generated
   */
  relational_expression getRelational_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.equality_expressionR#getRelational_expression <em>Relational expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relational expression</em>' containment reference.
   * @see #getRelational_expression()
   * @generated
   */
  void setRelational_expression(relational_expression value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.equality_expressionR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getequality_expressionR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<equality_expressionR> getRec();

} // equality_expressionR
