/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>IDENTIFIER</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getDr <em>Dr</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getIl <em>Il</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getA <em>A</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getName <em>Name</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIDENTIFIER()
 * @model
 * @generated
 */
public interface IDENTIFIER extends direct_declarator, identifier_list, identifier_listR, jump_statement, labeled_statement, designator, struct_or_union_specifier, postfix_expressionR, primary_expression
{
  /**
   * Returns the value of the '<em><b>Dr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Dr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dr</em>' containment reference.
   * @see #setDr(direct_declaratorR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIDENTIFIER_Dr()
   * @model containment="true"
   * @generated
   */
  direct_declaratorR getDr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getDr <em>Dr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dr</em>' containment reference.
   * @see #getDr()
   * @generated
   */
  void setDr(direct_declaratorR value);

  /**
   * Returns the value of the '<em><b>Il</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Il</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Il</em>' containment reference.
   * @see #setIl(identifier_listR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIDENTIFIER_Il()
   * @model containment="true"
   * @generated
   */
  identifier_listR getIl();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getIl <em>Il</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Il</em>' containment reference.
   * @see #getIl()
   * @generated
   */
  void setIl(identifier_listR value);

  /**
   * Returns the value of the '<em><b>A</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>A</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>A</em>' containment reference.
   * @see #setA(statement)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIDENTIFIER_A()
   * @model containment="true"
   * @generated
   */
  statement getA();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getA <em>A</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>A</em>' containment reference.
   * @see #getA()
   * @generated
   */
  void setA(statement value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getIDENTIFIER_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.IDENTIFIER#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // IDENTIFIER
