/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>inclusive or expression R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.inclusive_or_expressionR#getExclusive_or_expression <em>Exclusive or expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.inclusive_or_expressionR#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinclusive_or_expressionR()
 * @model
 * @generated
 */
public interface inclusive_or_expressionR extends EObject
{
  /**
   * Returns the value of the '<em><b>Exclusive or expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exclusive or expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exclusive or expression</em>' containment reference.
   * @see #setExclusive_or_expression(exclusive_or_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinclusive_or_expressionR_Exclusive_or_expression()
   * @model containment="true"
   * @generated
   */
  exclusive_or_expression getExclusive_or_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.inclusive_or_expressionR#getExclusive_or_expression <em>Exclusive or expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exclusive or expression</em>' containment reference.
   * @see #getExclusive_or_expression()
   * @generated
   */
  void setExclusive_or_expression(exclusive_or_expression value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.inclusive_or_expressionR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinclusive_or_expressionR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<inclusive_or_expressionR> getRec();

} // inclusive_or_expressionR
