/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>init declarator list R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.init_declarator_listR#getInit_declarator <em>Init declarator</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.init_declarator_listR#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinit_declarator_listR()
 * @model
 * @generated
 */
public interface init_declarator_listR extends EObject
{
  /**
   * Returns the value of the '<em><b>Init declarator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init declarator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init declarator</em>' containment reference.
   * @see #setInit_declarator(init_declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinit_declarator_listR_Init_declarator()
   * @model containment="true"
   * @generated
   */
  init_declarator getInit_declarator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.init_declarator_listR#getInit_declarator <em>Init declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init declarator</em>' containment reference.
   * @see #getInit_declarator()
   * @generated
   */
  void setInit_declarator(init_declarator value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.init_declarator_listR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getinit_declarator_listR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<init_declarator_listR> getRec();

} // init_declarator_listR
