/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>logical or expression R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.logical_or_expressionR#getLogical_and_expression <em>Logical and expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.logical_or_expressionR#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getlogical_or_expressionR()
 * @model
 * @generated
 */
public interface logical_or_expressionR extends EObject
{
  /**
   * Returns the value of the '<em><b>Logical and expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Logical and expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical and expression</em>' containment reference.
   * @see #setLogical_and_expression(logical_and_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getlogical_or_expressionR_Logical_and_expression()
   * @model containment="true"
   * @generated
   */
  logical_and_expression getLogical_and_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.logical_or_expressionR#getLogical_and_expression <em>Logical and expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical and expression</em>' containment reference.
   * @see #getLogical_and_expression()
   * @generated
   */
  void setLogical_and_expression(logical_and_expression value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.logical_or_expressionR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getlogical_or_expressionR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<logical_or_expressionR> getRec();

} // logical_or_expressionR
