/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>logical and expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.logical_and_expression#getInclusive_or_expression <em>Inclusive or expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.logical_and_expression#getLogical_and_expressionR <em>Logical and expression R</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getlogical_and_expression()
 * @model
 * @generated
 */
public interface logical_and_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Inclusive or expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Inclusive or expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inclusive or expression</em>' containment reference.
   * @see #setInclusive_or_expression(inclusive_or_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getlogical_and_expression_Inclusive_or_expression()
   * @model containment="true"
   * @generated
   */
  inclusive_or_expression getInclusive_or_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.logical_and_expression#getInclusive_or_expression <em>Inclusive or expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inclusive or expression</em>' containment reference.
   * @see #getInclusive_or_expression()
   * @generated
   */
  void setInclusive_or_expression(inclusive_or_expression value);

  /**
   * Returns the value of the '<em><b>Logical and expression R</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Logical and expression R</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical and expression R</em>' containment reference.
   * @see #setLogical_and_expressionR(logical_and_expressionR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getlogical_and_expression_Logical_and_expressionR()
   * @model containment="true"
   * @generated
   */
  logical_and_expressionR getLogical_and_expressionR();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.logical_and_expression#getLogical_and_expressionR <em>Logical and expression R</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical and expression R</em>' containment reference.
   * @see #getLogical_and_expressionR()
   * @generated
   */
  void setLogical_and_expressionR(logical_and_expressionR value);

} // logical_and_expression
