/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>multiplicative expression R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.multiplicative_expressionR#getCast_expression <em>Cast expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.multiplicative_expressionR#getRec <em>Rec</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getmultiplicative_expressionR()
 * @model
 * @generated
 */
public interface multiplicative_expressionR extends EObject
{
  /**
   * Returns the value of the '<em><b>Cast expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cast expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cast expression</em>' containment reference.
   * @see #setCast_expression(cast_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getmultiplicative_expressionR_Cast_expression()
   * @model containment="true"
   * @generated
   */
  cast_expression getCast_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.multiplicative_expressionR#getCast_expression <em>Cast expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cast expression</em>' containment reference.
   * @see #getCast_expression()
   * @generated
   */
  void setCast_expression(cast_expression value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.multiplicative_expressionR}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getmultiplicative_expressionR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<multiplicative_expressionR> getRec();

} // multiplicative_expressionR
