/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>parameter declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getDeclaration_specifiers2 <em>Declaration specifiers2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getDeclarator1 <em>Declarator1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getDeclaration_specifiers1 <em>Declaration specifiers1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getAbstract_declarator <em>Abstract declarator</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_declaration()
 * @model
 * @generated
 */
public interface parameter_declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaration specifiers2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration specifiers2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration specifiers2</em>' containment reference.
   * @see #setDeclaration_specifiers2(declaration_specifiers)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_declaration_Declaration_specifiers2()
   * @model containment="true"
   * @generated
   */
  declaration_specifiers getDeclaration_specifiers2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getDeclaration_specifiers2 <em>Declaration specifiers2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration specifiers2</em>' containment reference.
   * @see #getDeclaration_specifiers2()
   * @generated
   */
  void setDeclaration_specifiers2(declaration_specifiers value);

  /**
   * Returns the value of the '<em><b>Declarator1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declarator1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declarator1</em>' containment reference.
   * @see #setDeclarator1(declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_declaration_Declarator1()
   * @model containment="true"
   * @generated
   */
  declarator getDeclarator1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getDeclarator1 <em>Declarator1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declarator1</em>' containment reference.
   * @see #getDeclarator1()
   * @generated
   */
  void setDeclarator1(declarator value);

  /**
   * Returns the value of the '<em><b>Declaration specifiers1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaration specifiers1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaration specifiers1</em>' containment reference.
   * @see #setDeclaration_specifiers1(declaration_specifiers)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_declaration_Declaration_specifiers1()
   * @model containment="true"
   * @generated
   */
  declaration_specifiers getDeclaration_specifiers1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getDeclaration_specifiers1 <em>Declaration specifiers1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaration specifiers1</em>' containment reference.
   * @see #getDeclaration_specifiers1()
   * @generated
   */
  void setDeclaration_specifiers1(declaration_specifiers value);

  /**
   * Returns the value of the '<em><b>Abstract declarator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Abstract declarator</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract declarator</em>' containment reference.
   * @see #setAbstract_declarator(abstract_declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getparameter_declaration_Abstract_declarator()
   * @model containment="true"
   * @generated
   */
  abstract_declarator getAbstract_declarator();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.parameter_declaration#getAbstract_declarator <em>Abstract declarator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Abstract declarator</em>' containment reference.
   * @see #getAbstract_declarator()
   * @generated
   */
  void setAbstract_declarator(abstract_declarator value);

} // parameter_declaration
