/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>postfix expression R</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expressionR#getExpression <em>Expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expressionR#getRec <em>Rec</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.postfix_expressionR#getArgument_expression_list <em>Argument expression list</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expressionR()
 * @model
 * @generated
 */
public interface postfix_expressionR extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expressionR_Expression()
   * @model containment="true"
   * @generated
   */
  expression getExpression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.postfix_expressionR#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(expression value);

  /**
   * Returns the value of the '<em><b>Rec</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rec</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rec</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expressionR_Rec()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getRec();

  /**
   * Returns the value of the '<em><b>Argument expression list</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Argument expression list</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Argument expression list</em>' containment reference.
   * @see #setArgument_expression_list(argument_expression_list)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getpostfix_expressionR_Argument_expression_list()
   * @model containment="true"
   * @generated
   */
  argument_expression_list getArgument_expression_list();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.postfix_expressionR#getArgument_expression_list <em>Argument expression list</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Argument expression list</em>' containment reference.
   * @see #getArgument_expression_list()
   * @generated
   */
  void setArgument_expression_list(argument_expression_list value);

} // postfix_expressionR
