/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>relational expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.relational_expression#getShift_expression <em>Shift expression</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.relational_expression#getRe <em>Re</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getrelational_expression()
 * @model
 * @generated
 */
public interface relational_expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Shift expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Shift expression</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Shift expression</em>' containment reference.
   * @see #setShift_expression(shift_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getrelational_expression_Shift_expression()
   * @model containment="true"
   * @generated
   */
  shift_expression getShift_expression();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.relational_expression#getShift_expression <em>Shift expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Shift expression</em>' containment reference.
   * @see #getShift_expression()
   * @generated
   */
  void setShift_expression(shift_expression value);

  /**
   * Returns the value of the '<em><b>Re</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Re</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Re</em>' containment reference.
   * @see #setRe(relational_expressionR)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getrelational_expression_Re()
   * @model containment="true"
   * @generated
   */
  relational_expressionR getRe();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.relational_expression#getRe <em>Re</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Re</em>' containment reference.
   * @see #getRe()
   * @generated
   */
  void setRe(relational_expressionR value);

} // relational_expression
