/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>struct declarator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.struct_declarator#getDeclaratorx <em>Declaratorx</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.struct_declarator#getConstant_expression1 <em>Constant expression1</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstruct_declarator()
 * @model
 * @generated
 */
public interface struct_declarator extends EObject
{
  /**
   * Returns the value of the '<em><b>Declaratorx</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Declaratorx</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declaratorx</em>' containment reference.
   * @see #setDeclaratorx(declarator)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstruct_declarator_Declaratorx()
   * @model containment="true"
   * @generated
   */
  declarator getDeclaratorx();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.struct_declarator#getDeclaratorx <em>Declaratorx</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declaratorx</em>' containment reference.
   * @see #getDeclaratorx()
   * @generated
   */
  void setDeclaratorx(declarator value);

  /**
   * Returns the value of the '<em><b>Constant expression1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Constant expression1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant expression1</em>' containment reference.
   * @see #setConstant_expression1(constant_expression)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getstruct_declarator_Constant_expression1()
   * @model containment="true"
   * @generated
   */
  constant_expression getConstant_expression1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.struct_declarator#getConstant_expression1 <em>Constant expression1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant expression1</em>' containment reference.
   * @see #getConstant_expression1()
   * @generated
   */
  void setConstant_expression1(constant_expression value);

} // struct_declarator
